- name: Setting facts
  set_fact:
    myuser: "{{ myuser | default('viny') }}"

- name: Install packages
  apk:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - file
    - git
    - py3-rpigpio
    - libc6-compat

- import_tasks: myuser.yml
