- name: Generate random password for {{ myuser }}
  shell: openssl rand -base64 64 | cryptpw
  register: myuser_password
  changed_when: false

- name: Add user "{{ myuser }}"
  user:
    name: "{{ myuser }}"
    groups: gpio, wheel
    password: "{{ myuser_password.stdout }}"
    update_password: on_create

- name: Add home directory to LBU included files
  command: lbu add /home/{{ myuser }}

- name: Install sudo
  apk:
    name: sudo
    state: present

- name: Enable passwordless sudo for the wheel group
  lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- import_tasks: python.yml
