- name: Setup pitwo 
  hosts: pitwo 
  remote_user: pi
  become: true
  become_method: community.general.doas

  vars:
    base:
      packages:
        - libgpiod 

  tasks:
    - { import_role: name=alpine tasks_from=base }
    - { import_role: name=alpine tasks_from=lbu-commit, tags: ["always"] }
