- name: Setup pitwo
  hosts: pitwo

  tasks:
    - import_role:
        name: base
      tags: ['base']

    - import_role:
        name: devpi
      tags: ['custom']

    - import_role:
        name: lbu-commit
      tags: ['always']
