---
- name: Setup radiopapa
  hosts: radiopapa
  remote_user: pi
  become: true
  become_method: community.general.doas

  vars:
    radiogaga:
      dac: "Hifiberry2"

  tasks:
    - {import_role: name=radiogaga tasks_from=base}
    - {import_role: name=alpine tasks_from=lbu-commit}
